using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Plumbery.Domain.Entities {
    public partial class Country {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string DialCode { get; set; }

        public static List<Country> GetCountries() {
            List<Country> countries = new List<Country> {
                new Country{ Id = 1, Code="AFG", Name="Afghanistan", Region="South-Central Asia", DialCode="0093"},
                new Country{ Id = 2, Code="ALB", Name="Albania", Region="Southern Europe", DialCode="00355"},
                new Country{ Id = 3, Code="DZA", Name="Algeria", Region="Northern Africa", DialCode="00213"},
                new Country{ Id = 4, Code="ASM", Name="American Samoa", Region="Polynesia, Oceania", DialCode="0111684"},
                new Country{ Id = 5, Code="AND", Name="Andorra", Region="Southern Europe", DialCode="00376"},
                new Country{ Id = 6, Code="AGO", Name="Angola", Region="Central Africa", DialCode="00244"},
                new Country{ Id = 7, Code="AIA", Name="Anguilla", Region="Leeward Islands, Caribbean", DialCode="0111264"},
                new Country{ Id = 8, Code="ATG", Name="Antigua and Barbuda", Region="Leeward Islands, Caribbean", DialCode="0111268"},
                new Country{ Id = 9, Code="ARG", Name="Argentina", Region="Southern South America", DialCode="0054"},
                new Country{ Id = 10, Code="ARM", Name="Armenia", Region="Western Asia", DialCode="00374"},
                new Country{ Id = 11, Code="ABW", Name="Aruba", Region="Leeward Islands, Caribbean", DialCode="00297"},
                new Country{ Id = 12, Code="AUS", Name="Australia", Region="Australia/Oceania", DialCode="01161"},
                new Country{ Id = 13, Code="AUT", Name="Austria", Region="Western Europe", DialCode="0043"},
                new Country{ Id = 14, Code="AZE", Name="Azerbaijan", Region="Caucasus, Western Asia", DialCode="810994"},
                new Country{ Id = 15, Code="BHS", Name="Bahamas", Region="Caribbean", DialCode="0111242"},
                new Country{ Id = 16, Code="BHR", Name="Bahrain", Region="Arabian Peninsula, Middle East", DialCode="00973"},
                new Country{ Id = 17, Code="BGD", Name="Bangladesh", Region="South-Central Asia", DialCode="00880"},
                new Country{ Id = 18, Code="BRB", Name="Barbados", Region="Lesser Antilles, Caribbean", DialCode="0111246"},
                new Country{ Id = 19, Code="BLR", Name="Belarus", Region="Eastern Europe", DialCode="810375"},
                new Country{ Id = 20, Code="BEL", Name="Belgium", Region="Western Europe", DialCode="0032"},
                new Country{ Id = 21, Code="BLZ", Name="Belize", Region="Central America", DialCode="00501"},
                new Country{ Id = 22, Code="BEN", Name="Benin", Region="West Africa", DialCode="00229"},
                new Country{ Id = 23, Code="BMU", Name="Bermuda", Region="North America", DialCode="0111441"},
                new Country{ Id = 24, Code="BTN", Name="Bhutan", Region="South-Central Asia", DialCode="00975"},
                new Country{ Id = 25, Code="BOL", Name="Bolivia", Region="Central South America", DialCode="010591"},
                new Country{ Id = 26, Code="BIH", Name="Bosnia and Herzegovina", Region="Southern Europe", DialCode="00387"},
                new Country{ Id = 27, Code="BWA", Name="Botswana", Region="Southern Africa", DialCode="00267"},
                new Country{ Id = 28, Code="BRA", Name="Brazil", Region="Central Eastern South America", DialCode="01455"},
                new Country{ Id = 29, Code="BRN", Name="Brunei Darussalam", Region="Southeast Asia", DialCode="00673"},
                new Country{ Id = 30, Code="BGR", Name="Bulgaria", Region="Balkan, Eastern Europe", DialCode="00359"},
                new Country{ Id = 31, Code="BFA", Name="Burkina Faso", Region="West Africa", DialCode="00226"},
                new Country{ Id = 32, Code="BDI", Name="Burundi", Region="Eastern Africa, African Great Lakes", DialCode="00257"},
                new Country{ Id = 33, Code="KHM", Name="Cambodia", Region="South-East Asia", DialCode="00855"},
                new Country{ Id = 34, Code="CMR", Name="Cameroon", Region="Central Africa", DialCode="00237"},
                new Country{ Id = 35, Code="CAN", Name="Canada", Region="North North America", DialCode="0111"},
                new Country{ Id = 36, Code="CPV", Name="Cape Verde", Region="West Africa", DialCode="00238"},
                new Country{ Id = 37, Code="CYM", Name="Cayman Islands", Region="Greater Antilles, Caribbean", DialCode="0111345"},
                new Country{ Id = 38, Code="CAF", Name="Central African Republic", Region="Central Africa", DialCode="00236"},
                new Country{ Id = 39, Code="TCD", Name="Chad", Region="Central Africa", DialCode="015235"},
                new Country{ Id = 40, Code="CHL", Name="Chile", Region="Western South America", DialCode="0056"},
                new Country{ Id = 41, Code="CHN", Name="China", Region="Eastern Asia", DialCode="0086"},
                new Country{ Id = 42, Code="CXR", Name="Christmas Island", Region="Southeast Asia", DialCode="011618"},
                new Country{ Id = 43, Code="CCK", Name="Cocos (Keeling) Islands", Region="South-East Asia, Australia", DialCode="011618"},
                new Country{ Id = 44, Code="COL", Name="Colombia", Region="North West South America", DialCode="00557"},
                new Country{ Id = 45, Code="COM", Name="Comoros", Region="Eastern Africa", DialCode="00269"},
                new Country{ Id = 46, Code="CON", Name="Congo, Republic of (Brazzaville)", Region="Central Africa", DialCode="00242"},
                new Country{ Id = 47, Code="COK", Name="Cook Islands", Region="Polynesia, Oceania", DialCode="00682"},
                new Country{ Id = 48, Code="CRI", Name="Costa Rica", Region="Central America", DialCode="00506"},
                new Country{ Id = 49, Code="HRV", Name="Croatia", Region="Southern Europe", DialCode="00385"},
                new Country{ Id = 50, Code="CUB", Name="Cuba", Region="Greater Antilles, Caribbean", DialCode="11953"},
                new Country{ Id = 51, Code="CYP", Name="Cyprus", Region="Mediterranean, Western Asia", DialCode="00357"},
                new Country{ Id = 52, Code="CZE", Name="Czech Republic", Region="Eastern Europe", DialCode="00420"},
                new Country{ Id = 53, Code="DRC", Name="Democratic Republic of the Congo (Kinshasa)", Region="Central Africa", DialCode="00243"},
                new Country{ Id = 54, Code="DNK", Name="Denmark", Region="Northern Europe", DialCode="0045"},
                new Country{ Id = 55, Code="DJI", Name="Djibouti", Region="Eastern Africa", DialCode="00253"},
                new Country{ Id = 56, Code="DMA", Name="Dominica", Region="Lesser Antilles, Caribbean", DialCode="0111767"},
                new Country{ Id = 57, Code="DOM", Name="Dominican Republic", Region="Greater Antilles, Caribbean", DialCode="0111809"},
                new Country{ Id = 58, Code="ETM", Name="East Timor (Timor-Leste)", Region="South-East Asia", DialCode="--"},
                new Country{ Id = 59, Code="ECU", Name="Ecuador", Region="North West South America", DialCode="00593"},
                new Country{ Id = 60, Code="EGY", Name="Egypt", Region="Africa, Middle East", DialCode="0020"},
                new Country{ Id = 61, Code="SLV", Name="El Salvador", Region="Central America", DialCode="00503"},
                new Country{ Id = 62, Code="GNQ", Name="Equatorial Guinea", Region="Central Africa", DialCode="00240"},
                new Country{ Id = 63, Code="ERI", Name="Eritrea", Region="Eastern Africa", DialCode="00291"},
                new Country{ Id = 64, Code="EST", Name="Estonia", Region="Northern Europe", DialCode="00372"},
                new Country{ Id = 65, Code="ETH", Name="Ethiopia", Region="Eastern Africa", DialCode="00251"},
                new Country{ Id = 66, Code="FLD", Name="Falkland Islands", Region="Southern South America", DialCode="0500"},
                new Country{ Id = 67, Code="FRO", Name="Faroe Islands", Region="Northern Europe", DialCode="00298"},
                new Country{ Id = 68, Code="FJI", Name="Fiji", Region="Melanesia, Oceania", DialCode="00679"},
                new Country{ Id = 69, Code="FIN", Name="Finland", Region="Northern Europe", DialCode="00358"},
                new Country{ Id = 70, Code="FRA", Name="France", Region="Western Europe", DialCode="0033"},
                new Country{ Id = 71, Code="GUF", Name="French Guiana", Region="Northern South America", DialCode="00594"},
                new Country{ Id = 72, Code="PYF", Name="French Polynesia", Region="Polynesia, Oceania", DialCode="00689"},
                new Country{ Id = 73, Code="ATF", Name="French Southern Territories", Region="Southern South America, Antarctic", DialCode="--"},
                new Country{ Id = 74, Code="GAB", Name="Gabon", Region="Central Africa", DialCode="00241"},
                new Country{ Id = 75, Code="GMB", Name="Gambia", Region="West Africa", DialCode="00220"},
                new Country{ Id = 76, Code="GEO", Name="Georgia", Region="Western Asia", DialCode="810995"},
                new Country{ Id = 77, Code="DEU", Name="Germany", Region="Western Europe", DialCode="0049"},
                new Country{ Id = 78, Code="GHA", Name="Ghana", Region="West Africa", DialCode="00233"},
                new Country{ Id = 79, Code="GIB", Name="Gibraltar", Region="Southern Europe", DialCode="00350"},
                new Country{ Id = 80, Code="GBR", Name="Great Britain", Region="Northern Europe", DialCode="0044"},
                new Country{ Id = 81, Code="GRC", Name="Greece", Region="Southern Europe", DialCode="0030"},
                new Country{ Id = 82, Code="GRL", Name="Greenland", Region="North America", DialCode="009299"},
                new Country{ Id = 83, Code="GRD", Name="Grenada", Region="Lesser Antilles, Caribbean", DialCode="0111473"},
                new Country{ Id = 84, Code="GLP", Name="Guadeloupe", Region="Lesser Antilles, Caribbean", DialCode="00590"},
                new Country{ Id = 85, Code="GUM", Name="Guam", Region="Micronesia, Oceania", DialCode="0111671"},
                new Country{ Id = 86, Code="GTM", Name="Guatemala", Region="Central America", DialCode="00502"},
                new Country{ Id = 87, Code="GIN", Name="Guinea", Region="West Africa", DialCode="00224"},
                new Country{ Id = 88, Code="GNB", Name="Guinea-Bissau", Region="West Africa", DialCode="00245"},
                new Country{ Id = 89, Code="GUY", Name="Guyana", Region="North Eastern South America", DialCode="00592"},
                new Country{ Id = 90, Code="HTI", Name="Haiti", Region="Greater Antilles, Caribbean", DialCode="00509"},
                new Country{ Id = 91, Code="HYS", Name="Holy See", Region="Southern Europe within Italy", DialCode="00379"},
                new Country{ Id = 92, Code="HND", Name="Honduras", Region="Central America", DialCode="00504"},
                new Country{ Id = 93, Code="HKG", Name="Hong Kong", Region="Eastern Asia", DialCode="001852"},
                new Country{ Id = 94, Code="HUN", Name="Hungary", Region="Eastern Europe", DialCode="0036"},
                new Country{ Id = 95, Code="ISL", Name="Iceland", Region="Northern Europe", DialCode="00354"},
                new Country{ Id = 96, Code="IND", Name="India", Region="South-Central Asia", DialCode="0091"},
                new Country{ Id = 97, Code="IDN", Name="Indonesia", Region="Maritime South-East Asia", DialCode="00162"},
                new Country{ Id = 98, Code="IRA", Name="Iran (Islamic Republic of)", Region="South-Central Asia", DialCode="0098"},
                new Country{ Id = 99, Code="IRQ", Name="Iraq", Region="Middle East, Western Asia", DialCode="00964"},
                new Country{ Id = 100, Code="IRL", Name="Ireland", Region="Northern Europe", DialCode="00353"},
                new Country{ Id = 101, Code="ISR", Name="Israel", Region="Middle East, Western Asia", DialCode="00972"},
                new Country{ Id = 102, Code="ITA", Name="Italy", Region="Southern Europe", DialCode="0039"},
                new Country{ Id = 103, Code="IVC", Name="Ivory Coast", Region="West Africa", DialCode="--"},
                new Country{ Id = 104, Code="JAM", Name="Jamaica", Region="Greater Antilles, Caribbean", DialCode="0111876"},
                new Country{ Id = 105, Code="JPN", Name="Japan", Region="Eastern Asia", DialCode="01081"},
                new Country{ Id = 106, Code="JOR", Name="Jordan", Region="Middle East, Western Asia", DialCode="00962"},
                new Country{ Id = 107, Code="KAZ", Name="Kazakhstan", Region="Central Asia", DialCode="81076"},
                new Country{ Id = 108, Code="KEN", Name="Kenya", Region="Eastern Africa", DialCode="00254"},
                new Country{ Id = 109, Code="KIR", Name="Kiribati", Region="Micronesia, Oceania", DialCode="00686"},
                new Country{ Id = 110, Code="NKR", Name="Korea, Democratic People's Rep. (North Korea)", Region="Eastern Asia", DialCode="00850"},
                new Country{ Id = 111, Code="SKR", Name="Korea, Republic of (South Korea)", Region="Eastern Asia", DialCode="00182"},
                new Country{ Id = 112, Code="KOS", Name="Kosovo", Region="Southern Europe", DialCode="--"},
                new Country{ Id = 113, Code="KWT", Name="Kuwait", Region="Middle East, Western Asia", DialCode="00965"},
                new Country{ Id = 114, Code="KGZ", Name="Kyrgyzstan", Region="Central Asia", DialCode="00996"},
                new Country{ Id = 115, Code="LAO", Name="Lao, People's Democratic Republic", Region="South-East Asia", DialCode="00856"},
                new Country{ Id = 116, Code="LVA", Name="Latvia", Region="Northern Europe", DialCode="00371"},
                new Country{ Id = 117, Code="LBN", Name="Lebanon", Region="Middle East, Western Asia", DialCode="00961"},
                new Country{ Id = 118, Code="LSO", Name="Lesotho", Region="Southern Africa", DialCode="00266"},
                new Country{ Id = 119, Code="LBR", Name="Liberia", Region="West Africa", DialCode="00231"},
                new Country{ Id = 120, Code="LBY", Name="Libya", Region="Northern Africa", DialCode="00218"},
                new Country{ Id = 121, Code="LIE", Name="Liechtenstein", Region="Western Europe", DialCode="00423"},
                new Country{ Id = 122, Code="LTU", Name="Lithuania", Region="Northern Europe", DialCode="00370"},
                new Country{ Id = 123, Code="LUX", Name="Luxembourg", Region="Western Europe", DialCode="00352"},
                new Country{ Id = 124, Code="MCU", Name="Macau", Region="Eastern Asia", DialCode="00853"},
                new Country{ Id = 125, Code="MAC", Name="Macedonia, Rep. of", Region="Southern Europe", DialCode="00389"},
                new Country{ Id = 126, Code="MDG", Name="Madagascar", Region="Eastern Africa", DialCode="00261"},
                new Country{ Id = 127, Code="MWI", Name="Malawi", Region="Eastern Africa", DialCode="00265"},
                new Country{ Id = 128, Code="MYS", Name="Malaysia", Region="Southeast Asia", DialCode="0060"},
                new Country{ Id = 129, Code="MDV", Name="Maldives", Region="South-Central Asia", DialCode="00960"},
                new Country{ Id = 130, Code="MLI", Name="Mali", Region="West Africa", DialCode="00223"},
                new Country{ Id = 131, Code="MLT", Name="Malta", Region="Southern Europe", DialCode="00356"},
                new Country{ Id = 132, Code="MHL", Name="Marshall Islands", Region="Micronesia, Oceania", DialCode="00692"},
                new Country{ Id = 133, Code="MTQ", Name="Martinique", Region="Lesser Antilles, Caribbean", DialCode="00596"},
                new Country{ Id = 134, Code="MRT", Name="Mauritania", Region="West Africa", DialCode="00222"},
                new Country{ Id = 135, Code="MUS", Name="Mauritius", Region="Eastern Africa", DialCode="020230"},
                new Country{ Id = 136, Code="MYT", Name="Mayotte", Region="Eastern Africa", DialCode="00262"},
                new Country{ Id = 137, Code="MEX", Name="Mexico", Region="North America", DialCode="0052"},
                new Country{ Id = 138, Code="MIC", Name="Micronesia, Federal States of", Region="Micronesia, Oceania", DialCode="011691"},
                new Country{ Id = 139, Code="MDA", Name="Moldova, Republic of", Region="Eastern Europe", DialCode="00373"},
                new Country{ Id = 140, Code="MCO", Name="Monaco", Region="Southern Europe", DialCode="00377"},
                new Country{ Id = 141, Code="MNG", Name="Mongolia", Region="Eastern Asia", DialCode="001976"},
                new Country{ Id = 142, Code="MNE", Name="Montenegro", Region="Southern Europe", DialCode="099382"},
                new Country{ Id = 143, Code="MSR", Name="Montserrat", Region="Lesser Antilles, Caribbean", DialCode="0111664"},
                new Country{ Id = 144, Code="MAR", Name="Morocco", Region="Northern Africa", DialCode="00212"},
                new Country{ Id = 145, Code="MOZ", Name="Mozambique", Region="Eastern Africa", DialCode="00258"},
                new Country{ Id = 146, Code="MYA", Name="Myanmar, Burma", Region="Southeast Asia", DialCode="0095"},
                new Country{ Id = 147, Code="NAM", Name="Namibia", Region="Southern Africa", DialCode="00264"},
                new Country{ Id = 148, Code="NRU", Name="Nauru", Region="Micronesia, Oceania", DialCode="00674"},
                new Country{ Id = 149, Code="NPL", Name="Nepal", Region="South-Central Asia", DialCode="00977"},
                new Country{ Id = 150, Code="NLD", Name="Netherlands", Region="Western Europe", DialCode="0031"},
                new Country{ Id = 151, Code="NAN", Name="Netherlands Antilles", Region="Caribbean", DialCode="00599"},
                new Country{ Id = 152, Code="NCL", Name="New Caledonia", Region="Melanesia, Oceania", DialCode="00687"},
                new Country{ Id = 153, Code="NZL", Name="New Zealand", Region="Oceania; Australia", DialCode="0064"},
                new Country{ Id = 154, Code="NIC", Name="Nicaragua", Region="Central America", DialCode="00505"},
                new Country{ Id = 155, Code="NER", Name="Niger", Region="West Africa", DialCode="00227"},
                new Country{ Id = 156, Code="NGA", Name="Nigeria", Region="West Africa", DialCode="009234"},
                new Country{ Id = 157, Code="NIU", Name="Niue", Region="Polynesia, Oceania", DialCode="00683"},
                new Country{ Id = 158, Code="MNP", Name="Northern Mariana Islands", Region="Micronesia, Oceania", DialCode="0111670"},
                new Country{ Id = 159, Code="NOR", Name="Norway", Region="Northern Europe", DialCode="0047"},
                new Country{ Id = 160, Code="OMN", Name="Oman", Region="Middle East", DialCode="00968"},
                new Country{ Id = 161, Code="PAK", Name="Pakistan", Region="South-Central Asia", DialCode="0092"},
                new Country{ Id = 162, Code="PLW", Name="Palau", Region="Micronesia, Oceania", DialCode="00680"},
                new Country{ Id = 163, Code="PAL", Name="Palestinian territories", Region="Middle East, Western Asia", DialCode="00970"},
                new Country{ Id = 164, Code="PAN", Name="Panama", Region="Central America", DialCode="00507"},
                new Country{ Id = 165, Code="PNG", Name="Papua New Guinea", Region="Maritime Southeast Asia, Melanesia, Oceania", DialCode="005675"},
                new Country{ Id = 166, Code="PRY", Name="Paraguay", Region="Central South America", DialCode="002595"},
                new Country{ Id = 167, Code="PER", Name="Peru", Region="Western South America", DialCode="0051"},
                new Country{ Id = 168, Code="PHL", Name="Philippines", Region="Southeast Asia", DialCode="0063"},
                new Country{ Id = 169, Code="PIT", Name="Pitcairn Island", Region="Polynesia, Oceania", DialCode="00870"},
                new Country{ Id = 170, Code="POL", Name="Poland", Region="Eastern Europe", DialCode="0048"},
                new Country{ Id = 171, Code="PRT", Name="Portugal", Region="Southern Europe", DialCode="00351"},
                new Country{ Id = 172, Code="PRI", Name="Puerto Rico", Region="Greater Antilles, Caribbean", DialCode="0111787"},
                new Country{ Id = 173, Code="QAT", Name="Qatar", Region="Arabian Peninsula, Middle East", DialCode="00974"},
                new Country{ Id = 174, Code="REU", Name="Reunion Island", Region="Eastern Africa", DialCode="00262"},
                new Country{ Id = 175, Code="ROU", Name="Romania", Region="Eastern Europe", DialCode="0040"},
                new Country{ Id = 176, Code="RUS", Name="Russian Federation", Region="Eastern Europe - Northern Asia", DialCode="8107"},
                new Country{ Id = 177, Code="RWA", Name="Rwanda", Region="Eastern Africa, African Great Lakes", DialCode="00250"},
                new Country{ Id = 178, Code="KNA", Name="Saint Kitts and Nevis", Region="Lesser Antilles, Caribbean", DialCode="0111869"},
                new Country{ Id = 179, Code="LCA", Name="Saint Lucia", Region="Lesser Antilles, Caribbean", DialCode="0111758"},
                new Country{ Id = 180, Code="VCT", Name="Saint Vincent and the Grenadines", Region="Lesser Antilles, Caribbean", DialCode="0111784"},
                new Country{ Id = 181, Code="WSM", Name="Samoa", Region="Polynesia, Oceania", DialCode="00685"},
                new Country{ Id = 182, Code="SMR", Name="San Marino", Region="Southern Europe within Italy", DialCode="00378"},
                new Country{ Id = 183, Code="STP", Name="Sao Tome and Principe", Region="Central Africa", DialCode="00239"},
                new Country{ Id = 184, Code="SAU", Name="Saudi Arabia", Region="Arabian Peninsula, Middle East", DialCode="00966"},
                new Country{ Id = 185, Code="SEN", Name="Senegal", Region="West Africa", DialCode="00221"},
                new Country{ Id = 186, Code="SRB", Name="Serbia", Region="Southern Europe", DialCode="099381"},
                new Country{ Id = 187, Code="SYC", Name="Seychelles", Region="Eastern Africa", DialCode="00248"},
                new Country{ Id = 188, Code="SLE", Name="Sierra Leone", Region="West Africa", DialCode="00232"},
                new Country{ Id = 189, Code="SGP", Name="Singapore", Region="Southeast Asia", DialCode="00165"},
                new Country{ Id = 190, Code="SLK", Name="Slovakia (Slovak Republic)", Region="Eastern Europe", DialCode="00421"},
                new Country{ Id = 191, Code="SVN", Name="Slovenia", Region="Southern Europe", DialCode="00386"},
                new Country{ Id = 192, Code="SLB", Name="Solomon Islands", Region="Melanesia, Oceania", DialCode="00677"},
                new Country{ Id = 193, Code="SOM", Name="Somalia", Region="Eastern Africa", DialCode="00252"},
                new Country{ Id = 194, Code="ZAF", Name="South Africa", Region="Southern Africa", DialCode="00927"},
                new Country{ Id = 195, Code="SSD", Name="South Sudan", Region="East-Central Africa", DialCode="00249"},
                new Country{ Id = 196, Code="ESP", Name="Spain", Region="Southern Europe", DialCode="0034"},
                new Country{ Id = 197, Code="LKA", Name="Sri Lanka", Region="South-Central Asia", DialCode="0094"},
                new Country{ Id = 198, Code="SDN", Name="Sudan", Region="Northern Africa", DialCode="00249"},
                new Country{ Id = 199, Code="SUR", Name="Suriname", Region="North-Eastern South America", DialCode="00597"},
                new Country{ Id = 200, Code="SWZ", Name="Swaziland", Region="Southern Africa", DialCode="00268"},
                new Country{ Id = 201, Code="SWE", Name="Sweden", Region="Northern Europe", DialCode="0046"},
                new Country{ Id = 202, Code="CHE", Name="Switzerland", Region="Western Europe", DialCode="0041"},
                new Country{ Id = 203, Code="SYR", Name="Syria, Syrian Arab Republic", Region="Middle East, Western Asia", DialCode="00963"},
                new Country{ Id = 204, Code="TAI", Name="Taiwan (Republic of China)", Region="Eastern Asia", DialCode="002886"},
                new Country{ Id = 205, Code="TJK", Name="Tajikistan", Region="Central Asia", DialCode="810992"},
                new Country{ Id = 206, Code="TAN", Name="Tanzania; officially the United Republic of Tanzania", Region="Eastern Africa", DialCode="00255"},
                new Country{ Id = 207, Code="THA", Name="Thailand", Region="South-East Asia", DialCode="00166"},
                new Country{ Id = 208, Code="TIB", Name="Tibet", Region="South-Central Asia", DialCode="--"},
                new Country{ Id = 209, Code="TIM", Name="Timor-Leste (East Timor)", Region="Maritime South-East Asia", DialCode="670"},
                new Country{ Id = 210, Code="TGO", Name="Togo", Region="West Africa", DialCode="00228"},
                new Country{ Id = 211, Code="TKL", Name="Tokelau", Region="Oceania/Australia", DialCode="00690"},
                new Country{ Id = 212, Code="TON", Name="Tonga", Region="Polynesia, Oceania", DialCode="00676"},
                new Country{ Id = 213, Code="TTO", Name="Trinidad and Tobago", Region="Northern South America, Caribbean", DialCode="0111868"},
                new Country{ Id = 214, Code="TUN", Name="Tunisia", Region="Northern Africa", DialCode="00216"},
                new Country{ Id = 215, Code="TUR", Name="Turkey", Region="Southeastern Europe, Western Asia", DialCode="0090"},
                new Country{ Id = 216, Code="TKM", Name="Turkmenistan", Region="Central Asia", DialCode="810993"},
                new Country{ Id = 217, Code="TCA", Name="Turks and Caicos Islands", Region="Caribbean, parts of the Bahamas island chain.", DialCode="0111649"},
                new Country{ Id = 218, Code="TUV", Name="Tuvalu", Region="Polynesia, Oceania", DialCode="00688"},
                new Country{ Id = 219, Code="UGA", Name="Uganda", Region="Eastern Africa", DialCode="00256"},
                new Country{ Id = 220, Code="UKR", Name="Ukraine", Region="Eastern Europe", DialCode="810380"},
                new Country{ Id = 221, Code="ARE", Name="United Arab Emirates", Region="Arabian Peninsula, Middle East", DialCode="00971"},
                new Country{ Id = 222, Code="GBR", Name="United Kingdom", Region="Northern Europe", DialCode="0044"},
                new Country{ Id = 223, Code="USA", Name="United States", Region="North America", DialCode="0111"},
                new Country{ Id = 224, Code="URY", Name="Uruguay", Region="Central East South America", DialCode="00598"},
                new Country{ Id = 225, Code="UZB", Name="Uzbekistan", Region="Central Asia", DialCode="810998"},
                new Country{ Id = 226, Code="VUT", Name="Vanuatu", Region="Melanesia, Oceania", DialCode="00678"},
                new Country{ Id = 227, Code="VAT", Name="Vatican City State (Holy See)", Region="Southern Europe within Italy", DialCode="--"},
                new Country{ Id = 228, Code="VEN", Name="Venezuela", Region="Northern South America", DialCode="0058"},
                new Country{ Id = 229, Code="VTM", Name="Vietnam", Region="South-East Asia", DialCode="0084"},
                new Country{ Id = 230, Code="VBR", Name="Virgin Islands (British)", Region="Lesser Antilles, Caribbean", DialCode="0111284"},
                new Country{ Id = 231, Code="VUS", Name="Virgin Islands (U.S.)", Region="Lesser Antilles, Caribbean", DialCode="0111340"},
                new Country{ Id = 232, Code="WFI", Name="Wallis and Futuna Islands", Region="Polynesia, Oceania", DialCode="019681"},
                new Country{ Id = 233, Code="ESH", Name="Western Sahara", Region="Northern Africa", DialCode="--"},
                new Country{ Id = 234, Code="YEM", Name="Yemen", Region="Arabian Peninsula, Middle East", DialCode="00967"},
                new Country{ Id = 235, Code="ZMB", Name="Zambia", Region="Eastern Africa", DialCode="00260"},
                new Country{ Id = 236, Code="ZWE", Name="Zimbabwe", Region="Eastern Africa", DialCode="00263"}
            };
            return countries;
        }
    }
}
